### ISSUE TITLE
Problems with voice channels.

### ISSUE THREAD

**Issue by TheBlueSunny** [BundledSticksInkorperated/Discore#45]
Hi, with voice channels again there were problems, after running ConnectAsync the bot simply disconnects from the voice channel, in debug I found this message - "Can not retrieve the voice channel ID before connecting!"

**Comment by Francessco121** [comment]
Would you mind posting the code you're using to connect? 

That exception you're seeing logged occurs when something tries to get `DiscordVoiceConnection.VoiceChannelId` before `ConnectAsync` has been called or after the voice connection has been invalidated. This may be just happening as a side-effect of the bot disconnecting immediately.

**Comment by TheBlueSunny** [comment]
Even your example does not work - https://github.com/BundledSticksInkorperated/Discore.Samples/t

**Comment by Francessco121** [comment]
Sorry, but I just went back and tested the voice samples for v3.1.2, v4.0.0, and v4.1.0. All worked just fine.

Which version of Discore are you using? 

Are you using Windows 10? Those samples only include Windows binaries for ffmpeg, libsodium, and libopus.

Also it would greatly help if you could print out details from Discore's internal logger by doing something like:
```csharp
DiscoreLogger.MinimumLevel = DiscoreLogLevel.Debug;
DiscoreLogger.OnLog += DiscoreLogger_OnLog;

void DiscoreLogger_OnLog(object sender, DiscoreLogEventArgs e)
{
    Console.WriteLine($"[{e.Message.Type}] [{e.Message.Timestamp}] {e.Message.Content}");
}
```

If an error is occurring internally with Discore, there's a very high chance it will show up with that.

**Comment by TheBlueSunny** [comment]
> [Error] [24.01.18 17:46:28] [VoiceConnection:245177866986192898] [StartIPDiscovery] Failed start IP discovery: code = IsConnected, error = System.Net.Sockets.SocketException (0x80004005): Socket is already connected
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.SendToAsync(ArraySegment`1 buffer, SocketFlags socketFlags, EndPoint remoteEP)
   at Discore.Voice.DiscordVoiceConnection.<StartIPDiscovery>d__90.MoveNext()
[Error] [24.01.18 17:46:33] [VoiceConnection:245177866986192898] [DoFullConnect] Failed to connect: System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Take(CancellationToken cancellationToken)
   at Discore.Voice.DiscordVoiceConnection.<>c__DisplayClass91_0.<ReceiveIPDiscovery>b__0()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discore.Voice.DiscordVoiceConnection.<DoFullConnect>d__67.MoveNext()
[Debug] [24.01.18 17:46:33] [BaseWebSocket:VoiceWebSocket:245177866986192898] Disconnecting with code NormalClosure (1000)...
[Debug] [24.01.18 17:46:33] [BaseWebSocket:VoiceWebSocket:245177866986192898] [ReceiveLoop] Received close:  NormalClosure (1000)
[Debug] [24.01.18 17:46:33] [BaseWebSocket:VoiceWebSocket:245177866986192898] [ReceiveLoop] Completing close handshake with status NormalClosure (1000)...
[Debug] [24.01.18 17:46:33] [BaseWebSocket:VoiceWebSocket:245177866986192898] [ReceiveLoop] Completed close handshake.
[Debug] [24.01.18 17:46:33] [BaseWebSocket:VoiceWebSocket:245177866986192898] Disconnected.
[Debug] [24.01.18 17:46:33] [VoiceConnection:245177866986192898] [Invalidate] Invalidating voice connection...

**Comment by Francessco121** [comment]
Yep, turns out that's a bug alright. An interesting one as well. 

[This is the error you're getting](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx#WSAEISCONN), and if you read the description, note that the end says: "**Some implementations** also return this error if sendto is called on a connected SOCK_DGRAM socket". Looks like your OS/OS version actually handles this differently than mine!

Thankfully, this is actually a pretty easy fix, I just need to replace `SendToAsync` with `SendAsync` in the UDP code.

**Comment by TheBlueSunny** [comment]
Yes, I have Mac OS, I even tested dsharpplus, everything works there.

**Comment by Francessco121** [comment]
Ok, the potential fix is on master. Would you mind trying your bot with the latest commit? I don't have a Mac available to test on, and I'd prefer to know that this solved everything for you before doing a release.

**Comment by TheBlueSunny** [comment]
Yes, everything works, thank)

**Comment by Francessco121** [comment]
The fix for this is officially in v4.1.1, you should be able to update the package in an hour or so, NuGet is still publishing. :)
