### ISSUE TITLE
[Bug] Create Voice

### ISSUE THREAD

**Issue by TheBlueSunny** [BundledSticksInkorperated/Discore#46]
await DiscordClient.GetGuild(421412412412412).GetAwaiter().GetResult().CreateChannel(options);

Hi, the error.

BadRequest(400): _misc: Expected "Content-Type" header to be one of set(['application/json']).

   at Discore.Http.Net.RestClient.<ParseResponse>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discore.Http.Net.RestClient.<Send>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discore.Http.DiscordHttpClient.<CreateGuildChannel>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by TheBlueSunny** [comment]
I fixed it myself, but I would like you to release it officially :)

**Comment by TheBlueSunny** [comment]
And there was an incorrect Post request.

**Comment by TheBlueSunny** [comment]
And yet the mistake of making a userlimit.
It should be like this - user_limit

**Comment by Francessco121** [comment]
Thanks for providing the actual issues in the code! :) If you end up fixing something yourself, feel free to submit a pull-request next time, I'd be more than happy to merge it.
